# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(choices=[('A+ve', 'A+ve'), ('B+ve', 'B+ve'), ('A-ve', 'A-ve'), ('B-ve', 'B-ve'), ('O+ve', 'O+ve'), ('O-ve', 'O-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve')], default='', max_length=5),
        ),
    ]
