# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingComponents',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('billing_component', models.TextField(verbose_name='What is the cost about')),
                ('component_cost', models.PositiveIntegerField(verbose_name='What is the cost')),
                ('component_type', models.CharField(choices=[('mandatory', 'Mandatory like Consultation Cost'), ('optional', 'Optional'), ('onetime', 'OneTime Cost')], max_length=30, verbose_name='Mandatory or Optional or One Time Cost')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('dept_id', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=200, unique=True)),
                ('dept_description', models.TextField(blank=True, null=True)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='DepartmentsInHospital',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('hospital_dept_id', models.CharField(max_length=100, verbose_name='Internal Department ID')),
                ('no_of_doctors', models.IntegerField(verbose_name='How many doctors are there in this Dept')),
                ('dept_location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Where is this Dept located in the hospital')),
                ('dept_notes', models.TextField(blank=True, null=True, verbose_name='Any other specific details')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms.Department', to_field='dept_name', verbose_name='Select Department')),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('hospital_name', models.CharField(max_length=500, verbose_name='Name of the Hospital')),
                ('hospital_location', models.TextField(verbose_name='Full Address of the Hospital')),
                ('hospital_descrition', models.TextField(blank=True, null=True)),
                ('hospital_reg_no', models.CharField(default='', max_length=300, verbose_name='Hospital Registration Number')),
                ('hospital_registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='HospitalTypes',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('hospital_type', models.CharField(choices=[('clinic', 'Private Clinic'), ('24*7', 'A full fledged Hospital'), ('cancerclinic', 'Cancer Clinic')], max_length=120)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms.HospitalTypes', verbose_name='Type of Hospital'),
        ),
        migrations.AddField(
            model_name='departmentsinhospital',
            name='hospital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms.Hospital', verbose_name='Which Hopspital ?'),
        ),
        migrations.AddField(
            model_name='billingcomponents',
            name='hospital_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_ref_id', to='hms.Hospital'),
        ),
        migrations.AddField(
            model_name='billingcomponents',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
