# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 06:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrms', '0001_initial'),
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('is_invitation_notified', models.BooleanField(default=False)),
                ('is_user_logged_in', models.BooleanField(default=False)),
                ('hospital_invited_into', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_invited_into', to='hms.Hospital')),
                ('invite_user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
    ]
