# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrms', '0001_initial'),
        ('hms', '0002_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalUserRole',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('role', models.CharField(choices=[('receptionist', 'Receptionist'), ('doctor', 'Doctor'), ('hospital_admin', 'Hospital Admin'), ('accounts', 'Accounts'), ('accounts_admin', 'Accounts Admin')], max_length=20)),
                ('hospital_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_user_role_hospital_id', to='hms.Hospital')),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_user_role_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
    ]
