# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hms', '0003_hospitaluserrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='invited_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
