# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_invitations_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
