# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_auto_20180115_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcomponents',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingcomponents',
            name='hospital_ref_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_ref_id', to='hms.Hospital'),
        ),
        migrations.AlterField(
            model_name='billingcomponents',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
