# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrms', '__first__'),
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCMImages',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('pic', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('admission_reference_id', models.CharField(max_length=100)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_note', models.TextField()),
                ('inpatient_observation', models.TextField(blank=True, null=True)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='PatientAllergies',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('allergy', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='PatientEvents',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('tenant_id', models.CharField(default='Atom360', max_length=50)),
                ('visit_date', models.DateField(auto_now=True)),
                ('schedule_date', models.DateField()),
                ('clinical_advice', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('admission_required', models.BooleanField(default=False)),
                ('next_vist_date', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('admission_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phr.PatientAdmission')),
                ('dcmimages', models.ManyToManyField(blank=True, null=True, to='phr.DCMImages')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms.DepartmentsInHospital')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_id', to=settings.AUTH_USER_MODEL)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms.Hospital')),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='PatientInjection',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('injection_name', models.CharField(blank=True, max_length=200, null=True)),
                ('injection_dose', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='PatientMedicines',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('medicine_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('dosage', models.CharField(max_length=50)),
                ('cycle', models.CharField(choices=[('as_pain', 'Whenever you have pain'), ('101(A)', 'Morning & Night after Food'), ('101(B)', 'Morning & Night before Food'), ('111(B)', '3 times a day before Food'), ('111(A)', '3 times a day after Food'), ('001(A)', 'Only night after food'), ('001(B)', 'Only night before food')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='PatientOperation',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('operation_name', models.TextField()),
                ('operation_details', models.TextField()),
                ('tenant_id', models.CharField(default='Atom360', max_length=50)),
                ('hospital_id', models.CharField(max_length=50)),
                ('dept_id', models.CharField(max_length=50)),
                ('doctor_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.CreateModel(
            name='PatientSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_reported_symptoms', models.TextField(blank=True, null=True)),
                ('doctor_reported_symptoms', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTests',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('test_name', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('test_condition', models.TextField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
        migrations.AddField(
            model_name='patientevents',
            name='injection',
            field=models.ManyToManyField(to='phr.PatientInjection'),
        ),
        migrations.AddField(
            model_name='patientevents',
            name='medicines',
            field=models.ManyToManyField(to='phr.PatientMedicines'),
        ),
        migrations.AddField(
            model_name='patientevents',
            name='symptoms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phr.PatientSymptoms'),
        ),
        migrations.AddField(
            model_name='patientevents',
            name='tests',
            field=models.ManyToManyField(to='phr.PatientTests'),
        ),
        migrations.AddField(
            model_name='patientevents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phr.PatientOperation'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
