# Generated by Django 2.0 on 2017-12-28 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrms', '0001_initial'),
        ('phr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCMImages',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrms.DateTimeModel')),
                ('pic', models.ImageField(upload_to='dcm_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mrms.datetimemodel',),
        ),
    ]
