# Generated by Django 2.0 on 2017-12-27 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientevents',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms.DeptartmentsInHospital'),
        ),
        migrations.AlterField(
            model_name='patientevents',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientevents',
            name='hospital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms.Hospital'),
        ),
        migrations.AlterField(
            model_name='patientevents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
