# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phr', '0002_auto_20180115_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienttests',
            old_name='test_name',
            new_name='doctor_reported_tests',
        ),
        migrations.RemoveField(
            model_name='patientevents',
            name='is_open',
        ),
    ]
