# Generated by Django 2.0 on 2017-12-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phr', '0002_dcmimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcmimages',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
