# Generated by Django 2.0 on 2017-12-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeModel',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('updated_at',
                 models.DateTimeField(
                     auto_now=True)),
            ],
        ),
    ]
